# Generated by Django 3.2.8 on 2021-11-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0003_redeemableitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=20, null=True)),
                ('choinBalance', models.IntegerField(null=True)),
            ],
        ),
    ]
