# Generated by Django 3.2.8 on 2021-11-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0004_wallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
