# Generated by Django 3.2.8 on 2021-11-04 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_wallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
